server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location /web/static/ {
        try_files $uri =404;
    }

    location /web/manifest.json {
        try_files $uri =404;
    }

    location /web {
        try_files $uri $uri/ /index.html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}